export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_ERROR = 'AJAX_ERROR';
export const AJAX_END = 'AJAX_END';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REDIRECTED = 'REDIRECTED';

export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS';
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';

export const CREATE_FURNITURE_SUCCESS = 'CREATE_FURNITURE_SUCCESS';

//####################
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS'
export const CREATE_BOOK_ERROR = 'CREATE_BOOK_ERROR'
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS'
export const EDIT_BOOK_ERROR = 'EDIT_BOOK_ERROR'
export const DELETE_BOOK = 'DELETE_BOOK'

export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS'
export const CREATE_REVIEW_ERROR = 'CREATE_REVIEW_ERROR'
export const LIKE_PRODUCT = 'LIKE_PRODUCT'
export const UNLIKE_PRODUCT = 'UNLIKE_PRODUCT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const SYNC_CART = 'SYNC_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const SUBMIT_ORDER = 'SUBMIT_ORDER'
export const FETCH_USER_ORDERS = 'FETCH_USER_ORDERS'
export const FETCH_PENDING_ORDERS = 'FETCH_PENDING_ORDERS'
export const APPROVED_ORDER = 'APPROVED_ORDER'