export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_END = 'AJAX_END';
export const AJAX_ERROR = 'AJAX_ERROR';
export const AJAX_SUCCESS = 'AJAX_SUCCESS';

// Authentication
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REDIRECTED = 'REDIRECTED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// User
export const FETCH_LOGGEDIN_USERDATA_BEGIN = 'FETCH_LOGGEDIN_USERDATA_BEGIN';
export const FETCH_LOGGEDIN_USERDATA_SUCCESS = 'FETCH_LOGGEDIN_USERDATA_SUCCESS';
export const FETCH_LOGGEDIN_USERDATA_ERROR = 'FETCH_LOGGEDIN_USERDATA_ERROR';
export const UPDATE_LOGGEDIN_USERDATA = 'UPDATE_LOGGEDIN_USERDATA';

export const FETCH_TIMELINE_USERDATA_BEGIN = 'FETCH_TIMELINE_USERDATA_BEGIN';
export const FETCH_TIMELINE_USERDATA_SUCCESS = 'FETCH_TIMELINE_USERDATA_SUCCESS';
export const FETCH_TIMELINE_USERDATA_ERROR = 'FETCH_TIMELINE_USERDATA_ERROR';
export const UPDATE_TIMELINE_USERDATA = 'UPDATE_TIMELINE_USERDATA';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

// AllFriends
export const FETCH_ALLFRIENDS_BEGIN = 'FETCH_ALLFRIENDS_BEGIN';
export const FETCH_ALLFRIENDS_SUCCESS = 'FETCH_ALLFRIENDS_SUCCESS';
export const FETCH_ALLFRIENDS_ERROR = 'FETCH_ALLFRIENDS_ERROR';

// AllChatFriends
export const FETCH_ALLCHATFRIENDS_BEGIN = 'FETCH_ALLCHATFRIENDS_BEGIN';
export const FETCH_ALLCHATFRIENDS_SUCCESS = 'FETCH_ALLCHATFRIENDS_SUCCESS';
export const FETCH_ALLCHATFRIENDS_ERROR = 'FETCH_ALLCHATFRIENDS_ERROR';
export const EDIT_USERSTATUS = 'EDIT_USERSTATUS';

// Picture
export const FETCH_PICTURE_BEGIN = 'FETCH_PICTURE_BEGIN';
export const FETCH_PICTURE_SUCCESS = 'FETCH_PICTURE_SUCCESS';
export const FETCH_PICTURE_ERROR = 'FETCH_PICTURE_ERROR';

//Message
export const FETCH_ALLMESSAGES_SUCCESS = 'FETCH_ALLMESSAGES_SUCCESS';
export const FETCH_ALLMESSAGES_BEGIN = 'FETCH_ALLMESSAGES_BEGIN';
export const FETCH_ALLMESSAGES_ERROR = 'FETCH_ALLMESSAGES_ERROR';
export const ADD_MESSAGE = 'ADD_MESSAGE';

// Post
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_BEGIN = 'CREATE_POST_BEGIN';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const FETCH_ALLPOSTS_BEGIN = 'FETCH_ALLPOSTS_BEGIN';
export const FETCH_ALLPOSTS_SUCCESS = 'FETCH_ALLPOSTS_SUCCESS';
export const FETCH_ALLPOSTS_ERROR = 'FETCH_ALLPOSTS_ERROR';

export const REMOVE_POST_BEGIN = 'REMOVE_POST_BEGIN';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const REMOVE_POST_ERROR = 'REMOVE_POST_ERROR';

export const ADDLIKE_POST_BEGIN = 'ADDLIKE_POST_BEGIN';
export const ADDLIKE_POST_SUCCESS = 'ADDLIKE_POST_SUCCESS';
export const ADDLIKE_POST_ERROR = 'ADDLIKE_POST_ERROR';

// Comment
export const REMOVE_COMMENT_BEGIN = 'REMOVE_COMMENT_BEGIN';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';
export const REMOVE_COMMENT_ERROR = 'REMOVE_COMMENT_ERROR';

export const ADDLIKE_COMMENT_BEGIN = 'ADDLIKE_COMMENT_BEGIN';
export const ADDLIKE_COMMENT_SUCCESS = 'ADDLIKE_COMMENT_SUCCESS';
export const ADDLIKE_COMMENT_ERROR = 'ADDLIKE_COMMENT_ERROR';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_BEGIN = 'CREATE_COMMENT_BEGIN';
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR';
